steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/${PROJECT_ID}/${_IMAGE_NAME}/${_VERSION}', '.']

  - name: 'gcr.io/cloud-builders/kubectl'
    args: ['apply', '-f', 'kube/deployment.yaml']
    env:
    - 'CLOUDSDK_COMPUTE_ZONE=${_COMPUTE_ZONE}'
    - 'CLOUDSDK_CONTAINER_CLUSTER=${_CLUSTER}'

  - name: 'gcr.io/cloud-builders/kubectl'
    args:
    - set
    - image
    - deployment
    - buda-buffer-tweets-pipeline-crawler
    - crawler=gcr.io/${PROJECT_ID}/${_IMAGE_NAME}/${_VERSION}
    env:
    - 'CLOUDSDK_COMPUTE_ZONE=${_COMPUTE_ZONE}'
    - 'CLOUDSDK_CONTAINER_CLUSTER=${_CLUSTER}'

images: [
    'gcr.io/${PROJECT_ID}/${_IMAGE_NAME}/${_VERSION}'
]
